export const CONTENT_LIBRARY_KEY = 'upplai-design-studio-content-library-v1';
const clean = value => String(value || '').trim();
export function loadContentLibrary(storage = globalThis.localStorage) { try { const value = JSON.parse(storage.getItem(CONTENT_LIBRARY_KEY)); return { folders: Array.isArray(value?.folders) ? value.folders.filter(item => item?.id && clean(item.name)) : [] }; } catch { return { folders: [] }; } }
export function saveContentLibrary(value, storage = globalThis.localStorage) { const library = { folders: (value?.folders || []).map(item => ({ id: clean(item.id), name: clean(item.name).slice(0, 80) })).filter(item => item.id && item.name) }; storage.setItem(CONTENT_LIBRARY_KEY, JSON.stringify(library)); return library; }
export function createFolder(name, storage = globalThis.localStorage) { const label = clean(name).slice(0, 80); if (!label) throw new Error('Enter a folder name.'); const library = loadContentLibrary(storage); const folder = { id: `folder-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, name: label }; return { folder, library: saveContentLibrary({ folders: [...library.folders, folder] }, storage) }; }
export function organizeRows(rows, today, filters = {}) { const visible = rows.filter(row => !(row.archived && !filters.includeArchived)).filter(row => !filters.status || row.status === filters.status).filter(row => !filters.contentFormat || (row.contentFormat || 'single-image') === filters.contentFormat).filter(row => !filters.folderId || row.folderId === filters.folderId).filter(row => !filters.query || `${row.headline} ${row.supportingCopy || ''}`.toLowerCase().includes(filters.query.toLowerCase())); const group = row => row.date === today ? 0 : row.date > today ? 1 : 2; return visible.sort((a,b) => group(a)-group(b) || (group(a) === 1 ? a.date.localeCompare(b.date) : b.date.localeCompare(a.date)) || a.order-b.order); }
export function renameFolder(id, name, storage = globalThis.localStorage) { const label = clean(name).slice(0, 80); if (!label) throw new Error('Enter a folder name.'); const library = loadContentLibrary(storage); return saveContentLibrary({ folders: library.folders.map(folder => folder.id === id ? { ...folder, name: label } : folder) }, storage); }
export function deleteFolder(id, rows, storage = globalThis.localStorage) { const library = loadContentLibrary(storage); saveContentLibrary({ folders: library.folders.filter(folder => folder.id !== id) }, storage); return rows.map(row => row.folderId === id ? { ...row, folderId: null } : row); }
export const assignFolder = (rows, id, folderId) => rows.map(row => row.id === id ? { ...row, folderId: folderId || null } : row);
export const setArchived = (rows, id, archived) => rows.map(row => row.id === id ? { ...row, archived: Boolean(archived) } : row);
export function groupContentRows(rows, today) { const action = new Set(['ready','stale','failed','generated']); const active = rows.filter(row => !row.archived); return { today: active.filter(row => row.date === today && action.has(row.status)).sort((a,b)=>a.order-b.order), todayCompleted: active.filter(row => row.date === today && !action.has(row.status)).sort((a,b)=>a.order-b.order), upcoming: active.filter(row => row.date > today).sort((a,b)=>a.date.localeCompare(b.date)||a.order-b.order), library: active.filter(row => row.date < today).sort((a,b)=>b.date.localeCompare(a.date)||a.order-b.order) }; }
